[package]
name = "onefmt-find-biome"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
onefmt-plugin-utils = { git = "https://github.com/nahco314/onefmt-plugin-utils", version = "0.1.0" }
serde_json = "1.0.127"
